### ISSUE TITLE
beta21 - vl_imreadjpeg fails (Windows)

### ISSUE THREAD

**Issue by chrirupp** [vlfeat/matconvnet#677]
Hi all,

since updating to beta21 vl_imreadjpeg always returns 
"FILENAMES contains an entry that is not a string."
even with the same exact input as we had in beta20 working perfectly fine.
When we call it with options like vl_imreadjpeg(filenames, 'NumThreads', 4); we get
"The option name is not a string (argument number 2)"

Since this is an OS dependent function I would like to mention that this occurs on Windows. We will test it on one of our Linux machines as soon as we can. 

-Edit-
It works on Linux. Seems to be a Windows problem.

Thanks!
Chris

**Comment by chrirupp** [comment]
It seems that vlmxIsString() fails (vl_imreadjpeg.cu line 1378) in the current version on Windows even with valid strings. Temporary fix was to comment out this and the next two lines. Then image loading works again fine.

**Comment by chrirupp** [comment]
Ok, finally I found the problem: mexutils.h l31-35
`#ifdef  _WIN64
typedef unsigned __int64 ssize_t;
#else
typedef unsigned int ssize_t;
#endif
`
the problem is defining a supposedly signed type (ssize_t) to unsigned under Win64. Removing the unsigned resolves the problem.

**Comment by lenck** [comment]
Hey, thanks a lot for debugging it! :) I will try to look at it and apply your fix asap...

**Comment by lenck** [comment]
Thanks again for tracking it down, this was a bit nasty bug... It should be fixed in master, do you think you would be able to test it?

**Comment by chrirupp** [comment]
Currently all my machines are busy training, but I should be able to test it within 24h.

**Comment by chrirupp** [comment]
Dear Karel,

I suppose your fix works but your changes in imread_gdipus.cpp break the code again.

imread_gdiplus.cpp
SSSE3 instruction set enabled.
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(84) : warning C4800: 'UINT' : forcing value to bool 'true' or 'false'
(performance warning)
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(106) : error C2039: 'snprintf' : is not a member of 'std'
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(106) : error C3861: 'snprintf': identifier not found
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(148) : error C2039: 'snprintf' : s not a member of 'std'
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(148) : error C3861: 'snprintf': identifier not found
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(188) : error C2039: 'snprintf' : is not a member of 'std'
matconvnet\matlab\src\bits\impl\imread_gdiplus.cpp(188) : error C3861: 'snprintf': identifier not found

unfortunately, I currently don't have the time to track this down.

Cheers,
Chris

**Comment by lenck** [comment]
Thank you for testing it. If I can ask, what version of MSVC are you using?

**Comment by chrirupp** [comment]
Its MSVC 2013 Professional thus Visual C++ 12.0

**Comment by lenck** [comment]
It should be fixed now, hopefully... Thanks again for double checking it...

**Comment by mm12344** [comment]
Hi Chris,

I get the same problem with beta21 when I call it with the option  vl_imreadjpeg({rgbPath}). The {rgbPath} here is 
ans =  'data\JPEGImage.jpg'.
I have removed the unsigned from mexutils.h as you said
`#ifdef  _WIN64`
`typedef int ssize_t;`
`//typedef unsigned __int64 ssize_t;`
`#else`
`typedef unsigned int ssize_t;`
`#endif`

but I still get an error return
"Error using vl_imreadjpeg
FILENAMES contains an entry that is not a string."
Can you tell me why?

Thanks!
Clytze

**Comment by lenck** [comment]
Please use the latest version from GitHub... These bugs have been fixed
there...
