### ISSUE TITLE
vl_testnn for testing CPU has  2 Failed 2 Incomplete

### ISSUE THREAD

**Issue by sigmafang** [vlfeat/matconvnet#766]
After compling the vl_compilenn successfully, I ran vl_testnn and met the following problems.
vl_testnn
... ...

... ...
Failure Summary:
Name                                                                                                             Failed  Incomplete  Reason(s)
nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=dagnn)        X         X           Errored.
nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=simplenn)    X         X           Errored.
    
result = 

  1x1498 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration

Totals:
   1496 Passed, 2 Failed, 2 Incomplete.
   54.4386 seconds testing time.

My PC setting is Win7, 64bit, Matlab2014a, VS2010, CUDA7.5, NIVIDIA GTX750. The following combinations also have the same results:
  Win7, 64bit, Matlab2015b, VS2010, CUDA7.5, NIVIDIA GTX750
Win7, 64bit, Matlab2015b, VS2012, CUDA7.5, NIVIDIA GTX750
  Win7, 64bit, Matlab2014a, VS2010, CUDA6.5, NIVIDIA GTX750

Any suggestions will be appreciated. Thanks in advance.

**Comment by lenck** [comment]
Hi, yes, this test may fail few times, as there is a hard-coded error rate after single epoch of MNIST training. So in some cases, this does not pass (as it uses a random initialisation).
Can you maybe run it again and see what is the target error rate (it's in the MATLAB's error message after the failure) or just post the whole error rate message here?

**Comment by sigmafang** [comment]
@lenck 
Thanks for your attention. The whole error rate message is as follows:

 Running nnmnist
  Setting up nnmnist[dataType=single,device=cpu]
    Evaluating TestClassSetup: generators
    Evaluating TestClassSetup: init
  Done setting up nnmnist[dataType=single,device=cpu]
   Running nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=dagnn)
    Evaluating TestMethodSetup: seeds
    Evaluating Test: valErrorRate
downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

================================================================================
Uncaught error occurred in nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=dagnn).
The remainder of the test method will not run to completion.

    --------------
    Error Details:
    --------------
    Error using checkfilename>validateFilename (line 122)
    Function GUNZIP was unable to read URL ''http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz''.
    
    Error in checkfilename (line 49)
    [fullfilename, fid] = validateFilename( ...
    
    Error in gunzip>checkFilesURLInput (line 118)
       [fullFileName, url] = checkfilename(inputFiles{1}, validExtensions, fcnName, ...
    
    Error in gunzip (line 61)
    [files, url, urlFilename] = checkFilesURLInput(files, {'gz'},'FILES',mfilename);
    
    Error in cnn_mnist>getMnistImdb (line 98)
        gunzip(url, opts.dataDir) ;
    
    Error in cnn_mnist (line 32)
      imdb = getMnistImdb(opts) ;
    
    Error in nnmnist/valErrorRate (line 28)
          [~, info] = cnn_mnist('train', trainOpts, 'networkType', networkType);
    
================================================================================
   Done nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=dagnn)
   Running nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=simplenn)
    Evaluating TestMethodSetup: seeds
    Evaluating Test: valErrorRate
downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

================================================================================
Uncaught error occurred in nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=simplenn).
The remainder of the test method will not run to completion.

    --------------
    Error Details:
    --------------
    Error using checkfilename>validateFilename (line 122)
    Function GUNZIP was unable to read URL ''http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz''.
    
    Error in checkfilename (line 49)
    [fullfilename, fid] = validateFilename( ...
    
    Error in gunzip>checkFilesURLInput (line 118)
       [fullFileName, url] = checkfilename(inputFiles{1}, validExtensions, fcnName, ...
    
    Error in gunzip (line 61)
    [files, url, urlFilename] = checkFilesURLInput(files, {'gz'},'FILES',mfilename);
    
    Error in cnn_mnist>getMnistImdb (line 98)
        gunzip(url, opts.dataDir) ;
    
    Error in cnn_mnist (line 32)
      imdb = getMnistImdb(opts) ;
    
    Error in nnmnist/valErrorRate (line 28)
          [~, info] = cnn_mnist('train', trainOpts, 'networkType', networkType);
    
================================================================================
   Done nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=simplenn)
  Tearing down nnmnist[dataType=single,device=cpu]
  Done tearing down nnmnist[dataType=single,device=cpu]
 Done nnmnist
__________

I also downloaded the mnist data train-images-idx3-ubyte.gz. My computer is not connected to the Internet. 
Thanks very much for your time.

**Comment by eladar** [comment]
Hi I've similar error,
I've recently upgraded OS & Matlab versions (win10,2016b), I used to work with Win7  & Matlab 2016a.
After compiling MatConvNet as before (beta 20, CPU) i recived the following failure -

```
     Failure Summary:

     Name                                                                    Failed  Incomplete  Reason(s)
    =======================================================================================================
     nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=simplenn)    X         X       Errored.

```
Also looking for the exact error in the full report i got -

```

================================================================================
Error occurred in nnmnist[dataType=single,device=cpu]/valErrorRate(networkType=simplenn) and it did not run to completion.

    ---------
    Error ID:
    ---------
    'MATLAB:badsubscript'

    --------------
    Error Details:
    --------------
    Index exceeds matrix dimensions.
    
    Error in balanceBackgroundClass (line 53)
    newBg_trainSamplesInx=bg_trainSamplesInx(1:nBg);
    
    Error in cnn_train (line 130)
      state.train = balanceBackgroundClass(state.train, opts.bgClassLabel, imdb,opts.batchSize,opts.bg2fgRatio); %-ea
    
    Error in cnn_mnist (line 48)
    [net, info] = trainfn(net, imdb, getBatch(opts), ...
    
    Error in nnmnist/valErrorRate (line 28)
          [~, info] = cnn_mnist('train', trainOpts, 'networkType', networkType);
================================================================================

```

**Comment by lenck** [comment]
Ah, I see... For that you would need to probably rewrite the mnist example [here](https://github.com/vlfeat/matconvnet/blob/master/examples/mnist/cnn_mnist.m#L102), changing it from an URL to the path where you have downloaded the MNIST files...
But you have to downloaded all 4 files though:
```
files = {'train-images-idx3-ubyte', ...
         'train-labels-idx1-ubyte', ...
         't10k-images-idx3-ubyte', ...
         't10k-labels-idx1-ubyte'} ;
```

However I would not worry too much, if it just hasn't passed this test... This particular test is really just for the development, to see if the whole simplenn/dagnn pipeline is not broken...

**Comment by fmnoori** [comment]
I am still getting same issue.. any one found solution for it?
